// apps/web/src/components/Step1GraphBuild.tsx
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Loader2 } from 'lucide-react'

import { createSimulation } from '@/lib/api/simulation'
import type {
  BuildProgress,
  GraphData,
  OntologyItem,
  OntologyProgress,
  ProjectData,
  SystemLog,
} from '@/lib/process-types'
import { cn } from '@/lib/utils'

interface Step1Props {
  currentPhase: number // -1 上传 / 0 本体 / 1 构建 / 2 完成
  projectData: ProjectData | null
  ontologyProgress: OntologyProgress | null
  buildProgress: BuildProgress | null
  graphData: GraphData | null
  systemLogs: SystemLog[]
}

type SelectedItem = (OntologyItem & { itemType: 'entity' | 'relation' }) | null

/** 步骤一：图谱构建（本体生成 → GraphRAG 构建 → 完成进入环境搭建）。 */
export function Step1GraphBuild({
  currentPhase,
  projectData,
  ontologyProgress,
  buildProgress,
  graphData,
  systemLogs,
}: Step1Props) {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [selected, setSelected] = useState<SelectedItem>(null)
  const [creating, setCreating] = useState(false)
  const logRef = useRef<HTMLDivElement>(null)

  // 日志自动滚动到底部
  useEffect(() => {
    if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight
  }, [systemLogs.length])

  const stats = {
    nodes: graphData?.node_count ?? graphData?.nodes?.length ?? 0,
    edges: graphData?.edge_count ?? graphData?.edges?.length ?? 0,
    types: projectData?.ontology?.entity_types?.length ?? 0,
  }

  const entityName = (schemaName: string) =>
    projectData?.ontology?.entity_types?.find((e) => e.name === schemaName)?.name || schemaName

  // 进入环境搭建：创建 simulation 后跳转
  const handleEnterEnvSetup = async () => {
    if (!projectData?.project_id || !projectData?.graph_id) return
    setCreating(true)
    try {
      const res = await createSimulation({
        project_id: projectData.project_id,
        graph_id: projectData.graph_id,
        enable_twitter: true,
        enable_reddit: true,
      })
      if (res.success && res.data?.simulation_id) {
        navigate(`/simulation/${res.data.simulation_id}`)
      } else {
        alert(t('step1.createSimulationFailed', { error: res.error || t('common.unknownError') }))
      }
    } catch (err) {
      alert(t('step1.createSimulationException', { error: (err as Error).message }))
    } finally {
      setCreating(false)
    }
  }

  const badge = (cls: string, text: string) => (
    <span className={cn('rounded px-2 py-1 text-[10px] font-semibold uppercase', cls)}>{text}</span>
  )

  return (
    <div className="flex h-full flex-col overflow-hidden bg-muted/30">
      <div className="flex flex-1 flex-col gap-5 overflow-y-auto p-6">
        {/* 步骤 01：本体生成 */}
        <div
          className={cn(
            'relative rounded-lg border bg-card p-5 shadow-sm transition',
            currentPhase === 0 && 'border-[#FF5722] shadow-md',
          )}
        >
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="font-mono text-xl font-bold text-muted-foreground">01</span>
              <span className="text-sm font-semibold">{t('step1.ontologyGeneration')}</span>
            </div>
            {currentPhase > 0
              ? badge('bg-green-100 text-green-700', t('step1.ontologyCompleted'))
              : currentPhase === 0
                ? badge('bg-[#FF5722] text-white', t('step1.ontologyGenerating'))
                : badge('bg-muted text-muted-foreground', t('step1.ontologyPending'))}
          </div>
          <p className="mb-2 font-mono text-[10px] text-muted-foreground">
            POST /api/graph/ontology/generate
          </p>
          <p className="mb-4 text-xs leading-relaxed text-muted-foreground">
            {t('step1.ontologyDesc')}
          </p>

          {currentPhase === 0 && ontologyProgress && (
            <div className="mb-3 flex items-center gap-2 text-xs text-[#FF5722]">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              <span>{ontologyProgress.message || t('step1.analyzingDocs')}</span>
            </div>
          )}

          {/* 本体详情浮层 */}
          {selected && (
            <div className="absolute inset-x-5 bottom-5 top-16 z-10 flex flex-col overflow-hidden rounded-md border bg-background/95 shadow-lg backdrop-blur">
              <div className="flex items-center justify-between border-b bg-muted/50 px-4 py-3">
                <div className="flex items-center gap-2">
                  <span className="rounded bg-foreground px-1.5 py-0.5 text-[9px] font-bold uppercase text-background">
                    {selected.itemType === 'entity' ? t('step1.badgeEntity') : t('step1.badgeRelation')}
                  </span>
                  <span className="text-sm font-bold">{selected.name}</span>
                </div>
                <button onClick={() => setSelected(null)} className="text-muted-foreground hover:text-foreground">
                  ×
                </button>
              </div>
              <div className="flex-1 overflow-y-auto p-4">
                <p className="mb-4 border-b border-dashed pb-3 text-xs text-foreground/80">
                  {selected.description}
                </p>
                {!!selected.attributes?.length && (
                  <div className="mb-4">
                    <span className="mb-2 block text-[10px] font-semibold text-muted-foreground">
                      {t('step1.attributes')}
                    </span>
                    <div className="flex flex-col gap-1.5">
                      {selected.attributes.map((attr) => (
                        <div key={attr.name} className="flex flex-wrap items-baseline gap-1.5 rounded bg-muted/50 p-1 text-[11px]">
                          <span className="font-mono font-semibold">{attr.name}</span>
                          <span className="text-[10px] text-muted-foreground">({attr.type})</span>
                          <span className="flex-1 text-muted-foreground">{attr.description}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                {!!selected.examples?.length && (
                  <div className="mb-4">
                    <span className="mb-2 block text-[10px] font-semibold text-muted-foreground">
                      {t('step1.examples')}
                    </span>
                    <div className="flex flex-wrap gap-1.5">
                      {selected.examples.map((ex) => (
                        <span key={ex} className="rounded-full border px-2 py-0.5 text-[11px] text-muted-foreground">
                          {ex}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {!!selected.source_targets?.length && (
                  <div className="mb-4">
                    <span className="mb-2 block text-[10px] font-semibold text-muted-foreground">
                      {t('step1.connections')}
                    </span>
                    <div className="flex flex-col gap-1.5">
                      {selected.source_targets.map((conn, idx) => (
                        <div key={idx} className="flex items-center gap-2 rounded bg-muted/50 p-1.5 font-mono text-[11px]">
                          <span className="font-semibold">{entityName(conn.source)}</span>
                          <span className="text-muted-foreground">→</span>
                          <span className="font-semibold">{entityName(conn.target)}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* 实体类型标签 */}
          {projectData?.ontology?.entity_types && (
            <div className={cn('mt-3 transition', selected && 'pointer-events-none opacity-30')}>
              <span className="mb-2 block text-[10px] font-semibold text-muted-foreground">
                {t('step1.generatedEntityTypes')}
              </span>
              <div className="flex flex-wrap gap-2">
                {projectData.ontology.entity_types.map((entity) => (
                  <span
                    key={entity.name}
                    onClick={() => setSelected({ ...entity, itemType: 'entity' })}
                    className="cursor-pointer rounded border bg-muted px-2.5 py-1 font-mono text-[11px] hover:bg-accent"
                  >
                    {entity.name}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* 关系类型标签 */}
          {projectData?.ontology?.edge_types && (
            <div className={cn('mt-3 transition', selected && 'pointer-events-none opacity-30')}>
              <span className="mb-2 block text-[10px] font-semibold text-muted-foreground">
                {t('step1.generatedRelationTypes')}
              </span>
              <div className="flex flex-wrap gap-2">
                {projectData.ontology.edge_types.map((rel) => (
                  <span
                    key={rel.name}
                    onClick={() => setSelected({ ...rel, itemType: 'relation' })}
                    className="cursor-pointer rounded border bg-muted px-2.5 py-1 font-mono text-[11px] hover:bg-accent"
                  >
                    {rel.name}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* 步骤 02：图谱构建 */}
        <div
          className={cn(
            'rounded-lg border bg-card p-5 shadow-sm transition',
            currentPhase === 1 && 'border-[#FF5722] shadow-md',
          )}
        >
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="font-mono text-xl font-bold text-muted-foreground">02</span>
              <span className="text-sm font-semibold">{t('step1.graphRagBuild')}</span>
            </div>
            {currentPhase > 1
              ? badge('bg-green-100 text-green-700', t('step1.ontologyCompleted'))
              : currentPhase === 1
                ? badge('bg-[#FF5722] text-white', `${buildProgress?.progress || 0}%`)
                : badge('bg-muted text-muted-foreground', t('step1.ontologyPending'))}
          </div>
          <p className="mb-2 font-mono text-[10px] text-muted-foreground">POST /api/graph/build</p>
          <p className="mb-4 text-xs leading-relaxed text-muted-foreground">{t('step1.graphRagDesc')}</p>
          <div className="grid grid-cols-3 gap-3 rounded-md bg-muted/50 p-4">
            {[
              { v: stats.nodes, l: t('step1.entityNodes') },
              { v: stats.edges, l: t('step1.relationEdges') },
              { v: stats.types, l: t('step1.schemaTypes') },
            ].map((s, i) => (
              <div key={i} className="text-center">
                <span className="block font-mono text-xl font-bold">{s.v}</span>
                <span className="mt-1 block text-[9px] uppercase text-muted-foreground">{s.l}</span>
              </div>
            ))}
          </div>
        </div>

        {/* 步骤 03：完成 */}
        <div
          className={cn(
            'rounded-lg border bg-card p-5 shadow-sm transition',
            currentPhase >= 2 && 'border-[#FF5722] shadow-md',
          )}
        >
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="font-mono text-xl font-bold text-muted-foreground">03</span>
              <span className="text-sm font-semibold">{t('step1.buildComplete')}</span>
            </div>
            {currentPhase >= 2 && badge('bg-[#FF5722] text-white', t('step1.inProgress'))}
          </div>
          <p className="mb-2 font-mono text-[10px] text-muted-foreground">POST /api/simulation/create</p>
          <p className="mb-4 text-xs leading-relaxed text-muted-foreground">{t('step1.buildCompleteDesc')}</p>
          <button
            onClick={handleEnterEnvSetup}
            disabled={currentPhase < 2 || creating}
            className="flex w-full items-center justify-center gap-2 rounded bg-foreground py-3.5 text-xs font-semibold text-background transition hover:opacity-80 disabled:cursor-not-allowed disabled:opacity-40"
          >
            {creating && <Loader2 className="h-3.5 w-3.5 animate-spin" />}
            {creating ? t('step1.creating') : `${t('step1.enterEnvSetup')} ➝`}
          </button>
        </div>
      </div>

      {/* 系统日志终端 */}
      <div className="flex-shrink-0 border-t border-zinc-800 bg-black p-4 font-mono text-zinc-300">
        <div className="mb-2 flex justify-between border-b border-zinc-700 pb-2 text-[10px] text-zinc-500">
          <span>{t('common.systemDashboard')}</span>
          <span>{projectData?.project_id || 'NO_PROJECT'}</span>
        </div>
        <div ref={logRef} className="flex h-20 flex-col gap-1 overflow-y-auto pr-1">
          {systemLogs.map((log, idx) => (
            <div key={idx} className="flex gap-3 text-[11px] leading-relaxed">
              <span className="min-w-[75px] text-zinc-600">{log.time}</span>
              <span className="break-all text-zinc-300">{log.msg}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/Step1GraphBuild.vue
<template>
  <div class="workbench-panel">
    <div class="scroll-container">
      <!-- Step 01: Ontology -->
      <div class="step-card" :class="{ 'active': currentPhase === 0, 'completed': currentPhase > 0 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">01</span>
            <span class="step-title">{{ $t('step1.ontologyGeneration') }}</span>
          </div>
          <div class="step-status">
            <span v-if="currentPhase > 0" class="badge success">{{ $t('step1.ontologyCompleted') }}</span>
            <span v-else-if="currentPhase === 0" class="badge processing">{{ $t('step1.ontologyGenerating') }}</span>
            <span v-else class="badge pending">{{ $t('step1.ontologyPending') }}</span>
          </div>
        </div>
        
        <div class="card-content">
          <p class="api-note">POST /api/graph/ontology/generate</p>
          <p class="description">
            {{ $t('step1.ontologyDesc') }}
          </p>

          <!-- Loading / Progress -->
          <div v-if="currentPhase === 0 && ontologyProgress" class="progress-section">
            <div class="spinner-sm"></div>
            <span>{{ ontologyProgress.message || $t('step1.analyzingDocs') }}</span>
          </div>

          <!-- Detail Overlay -->
          <div v-if="selectedOntologyItem" class="ontology-detail-overlay">
            <div class="detail-header">
               <div class="detail-title-group">
                  <span class="detail-type-badge">{{ selectedOntologyItem.itemType === 'entity' ? $t('step1.badgeEntity') : $t('step1.badgeRelation') }}</span>
                  <span class="detail-name">{{ displayName(selectedOntologyItem) }}</span>
               </div>
               <button class="close-btn" @click="selectedOntologyItem = null">×</button>
            </div>
            <div class="detail-body">
               <div class="detail-desc">{{ selectedOntologyItem.description }}</div>
               
               <!-- Attributes -->
               <div class="detail-section" v-if="selectedOntologyItem.attributes?.length">
                  <span class="section-label">{{ $t('step1.attributes') }}</span>
                  <div class="attr-list">
                     <div v-for="attr in selectedOntologyItem.attributes" :key="attr.name" class="attr-item">
                        <span class="attr-name">{{ attr.name }}</span>
                        <span class="attr-type">({{ attr.type }})</span>
                        <span class="attr-desc">{{ attr.description }}</span>
                     </div>
                  </div>
               </div>

               <!-- Examples (Entity) -->
               <div class="detail-section" v-if="selectedOntologyItem.examples?.length">
                  <span class="section-label">{{ $t('step1.examples') }}</span>
                  <div class="example-list">
                     <span v-for="ex in selectedOntologyItem.examples" :key="ex" class="example-tag">{{ ex }}</span>
                  </div>
               </div>

               <!-- Source/Target (Relation) -->
               <div class="detail-section" v-if="selectedOntologyItem.source_targets?.length">
                  <span class="section-label">{{ $t('step1.connections') }}</span>
                  <div class="conn-list">
                     <div v-for="(conn, idx) in selectedOntologyItem.source_targets" :key="idx" class="conn-item">
                        <span class="conn-node">{{ entityDisplayName(conn.source) }}</span>
                        <span class="conn-arrow">→</span>
                        <span class="conn-node">{{ entityDisplayName(conn.target) }}</span>
                     </div>
                  </div>
               </div>
            </div>
          </div>

          <!-- Generated Entity Tags -->
          <div v-if="projectData?.ontology?.entity_types" class="tags-container" :class="{ 'dimmed': selectedOntologyItem }">
            <span class="tag-label">{{ $t('step1.generatedEntityTypes') }}</span>
            <div class="tags-list">
              <span 
                v-for="entity in projectData.ontology.entity_types" 
                :key="entity.name" 
                class="entity-tag clickable"
                @click="selectOntologyItem(entity, 'entity')"
              >
                {{ displayName(entity) }}
              </span>
            </div>
          </div>

          <!-- Generated Relation Tags -->
          <div v-if="projectData?.ontology?.edge_types" class="tags-container" :class="{ 'dimmed': selectedOntologyItem }">
            <span class="tag-label">{{ $t('step1.generatedRelationTypes') }}</span>
            <div class="tags-list">
              <span 
                v-for="rel in projectData.ontology.edge_types" 
                :key="rel.name" 
                class="entity-tag clickable"
                @click="selectOntologyItem(rel, 'relation')"
              >
                {{ displayName(rel) }}
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- Step 02: Graph Build -->
      <div class="step-card" :class="{ 'active': currentPhase === 1, 'completed': currentPhase > 1 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">02</span>
            <span class="step-title">{{ $t('step1.graphRagBuild') }}</span>
          </div>
          <div class="step-status">
            <span v-if="currentPhase > 1" class="badge success">{{ $t('step1.ontologyCompleted') }}</span>
            <span v-else-if="currentPhase === 1" class="badge processing">{{ buildProgress?.progress || 0 }}%</span>
            <span v-else class="badge pending">{{ $t('step1.ontologyPending') }}</span>
          </div>
        </div>

        <div class="card-content">
          <p class="api-note">POST /api/graph/build</p>
          <p class="description">
            {{ $t('step1.graphRagDesc') }}
          </p>
          
          <!-- Stats Cards -->
          <div class="stats-grid">
            <div class="stat-card">
              <span class="stat-value">{{ graphStats.nodes }}</span>
              <span class="stat-label">{{ $t('step1.entityNodes') }}</span>
            </div>
            <div class="stat-card">
              <span class="stat-value">{{ graphStats.edges }}</span>
              <span class="stat-label">{{ $t('step1.relationEdges') }}</span>
            </div>
            <div class="stat-card">
              <span class="stat-value">{{ graphStats.types }}</span>
              <span class="stat-label">{{ $t('step1.schemaTypes') }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Step 03: Complete -->
      <div class="step-card" :class="{ 'active': currentPhase === 2, 'completed': currentPhase >= 2 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">03</span>
            <span class="step-title">{{ $t('step1.buildComplete') }}</span>
          </div>
          <div class="step-status">
            <span v-if="currentPhase >= 2" class="badge accent">{{ $t('step1.inProgress') }}</span>
          </div>
        </div>
        
        <div class="card-content">
          <p class="api-note">POST /api/simulation/create</p>
          <p class="description">{{ $t('step1.buildCompleteDesc') }}</p>
          <button 
            class="action-btn" 
            :disabled="currentPhase < 2 || creatingSimulation"
            @click="handleEnterEnvSetup"
          >
            <span v-if="creatingSimulation" class="spinner-sm"></span>
            {{ creatingSimulation ? $t('step1.creating') : $t('step1.enterEnvSetup') + ' ➝' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Bottom Info / Logs -->
    <div class="system-logs">
      <div class="log-header">
        <span class="log-title">{{ $t('common.systemDashboard') }}</span>
        <span class="log-id">{{ projectData?.project_id || 'NO_PROJECT' }}</span>
      </div>
      <div class="log-content" ref="logContent">
        <div class="log-line" v-for="(log, idx) in systemLogs" :key="idx">
          <span class="log-time">{{ log.time }}</span>
          <span class="log-msg">{{ log.msg }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, ref, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { createSimulation } from '../api/simulation'

const router = useRouter()
const { t } = useI18n()

const props = defineProps({
  currentPhase: { type: Number, default: 0 },
  projectData: Object,
  ontologyProgress: Object,
  buildProgress: Object,
  graphData: Object,
  systemLogs: { type: Array, default: () => [] }
})

defineEmits(['next-step'])

const selectedOntologyItem = ref(null)
const logContent = ref(null)
const creatingSimulation = ref(false)

const displayName = (item) => item?.name || ''

const entityDisplayName = (schemaName) => {
  const entity = props.projectData?.ontology?.entity_types?.find(item => item.name === schemaName)
  return entity?.name || schemaName
}

// 进入环境搭建 - 创建 simulation 并跳转
const handleEnterEnvSetup = async () => {
  if (!props.projectData?.project_id || !props.projectData?.graph_id) {
    console.error('缺少项目或图谱信息')
    return
  }
  
  creatingSimulation.value = true
  
  try {
    const res = await createSimulation({
      project_id: props.projectData.project_id,
      graph_id: props.projectData.graph_id,
      enable_twitter: true,
      enable_reddit: true
    })
    
    if (res.success && res.data?.simulation_id) {
      // 跳转到 simulation 页面
      router.push({
        name: 'Simulation',
        params: { simulationId: res.data.simulation_id }
      })
    } else {
      console.error('创建模拟失败:', res.error)
      alert(t('step1.createSimulationFailed', { error: res.error || t('common.unknownError') }))
    }
  } catch (err) {
    console.error('创建模拟异常:', err)
    alert(t('step1.createSimulationException', { error: err.message }))
  } finally {
    creatingSimulation.value = false
  }
}

const selectOntologyItem = (item, type) => {
  selectedOntologyItem.value = { ...item, itemType: type }
}

const graphStats = computed(() => {
  const nodes = props.graphData?.node_count || props.graphData?.nodes?.length || 0
  const edges = props.graphData?.edge_count || props.graphData?.edges?.length || 0
  const types = props.projectData?.ontology?.entity_types?.length || 0
  return { nodes, edges, types }
})

const formatDate = (dateStr) => {
  if (!dateStr) return '--:--:--'
  const d = new Date(dateStr)
  return d.toLocaleTimeString('en-US', { hour12: false }) + '.' + d.getMilliseconds()
}

// Auto-scroll logs
watch(() => props.systemLogs.length, () => {
  nextTick(() => {
    if (logContent.value) {
      logContent.value.scrollTop = logContent.value.scrollHeight
    }
  })
})
</script>

<style scoped>
.workbench-panel {
  height: 100%;
  background-color: #FAFAFA;
  display: flex;
  flex-direction: column;
  position: relative;
  overflow: hidden;
}

.scroll-container {
  flex: 1;
  overflow-y: auto;
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.step-card {
  background: #FFF;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.04);
  border: 1px solid #EAEAEA;
  transition: all 0.3s ease;
  position: relative; /* For absolute overlay */
}

.step-card.active {
  border-color: #FF5722;
  box-shadow: 0 4px 12px rgba(255, 87, 34, 0.08);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.step-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.step-num {
  font-family: 'JetBrains Mono', monospace;
  font-size: 20px;
  font-weight: 700;
  color: #E0E0E0;
}

.step-card.active .step-num,
.step-card.completed .step-num {
  color: #000;
}

.step-title {
  font-weight: 600;
  font-size: 14px;
  letter-spacing: 0.5px;
}

.badge {
  font-size: 10px;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: 600;
  text-transform: uppercase;
}

.badge.success { background: #E8F5E9; color: #2E7D32; }
.badge.processing { background: #FF5722; color: #FFF; }
.badge.accent { background: #FF5722; color: #FFF; }
.badge.pending { background: #F5F5F5; color: #999; }

.api-note {
  font-family: 'JetBrains Mono', monospace;
  font-size: 10px;
  color: #999;
  margin-bottom: 8px;
}

.description {
  font-size: 12px;
  color: #666;
  line-height: 1.5;
  margin-bottom: 16px;
}

/* Step 01 Tags */
.tags-container {
  margin-top: 12px;
  transition: opacity 0.3s;
}

.tags-container.dimmed {
    opacity: 0.3;
    pointer-events: none;
}

.tag-label {
  display: block;
  font-size: 10px;
  color: #AAA;
  margin-bottom: 8px;
  font-weight: 600;
}

.tags-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.entity-tag {
  background: #F5F5F5;
  border: 1px solid #EEE;
  padding: 4px 10px;
  border-radius: 4px;
  font-size: 11px;
  color: #333;
  font-family: 'JetBrains Mono', monospace;
  transition: all 0.2s;
}

.entity-tag.clickable {
    cursor: pointer;
}

.entity-tag.clickable:hover {
    background: #E0E0E0;
    border-color: #CCC;
}

/* Ontology Detail Overlay */
.ontology-detail-overlay {
    position: absolute;
    top: 60px; /* Below header roughly */
    left: 20px;
    right: 20px;
    bottom: 20px;
    background: rgba(255, 255, 255, 0.98);
    backdrop-filter: blur(4px);
    z-index: 10;
    border: 1px solid #EAEAEA;
    box-shadow: 0 4px 20px rgba(0,0,0,0.05);
    border-radius: 6px;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    animation: fadeIn 0.2s ease-out;
}

@keyframes fadeIn { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }

.detail-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 16px;
    border-bottom: 1px solid #EAEAEA;
    background: #FAFAFA;
}

.detail-title-group {
    display: flex;
    align-items: center;
    gap: 8px;
}

.detail-type-badge {
    font-size: 9px;
    font-weight: 700;
    color: #FFF;
    background: #000;
    padding: 2px 6px;
    border-radius: 2px;
    text-transform: uppercase;
}

.detail-name {
    font-size: 14px;
    font-weight: 700;
}

.detail-schema-name {
    font-size: 11px;
    color: #999;
    font-family: 'JetBrains Mono', monospace;
}

.close-btn {
    background: none;
    border: none;
    font-size: 18px;
    color: #999;
    cursor: pointer;
    line-height: 1;
}

.close-btn:hover {
    color: #333;
}

.detail-body {
    flex: 1;
    overflow-y: auto;
    padding: 16px;
}

.detail-desc {
    font-size: 12px;
    color: #444;
    line-height: 1.5;
    margin-bottom: 16px;
    padding-bottom: 12px;
    border-bottom: 1px dashed #EAEAEA;
}

.detail-section {
    margin-bottom: 16px;
}

.section-label {
    display: block;
    font-size: 10px;
    font-weight: 600;
    color: #AAA;
    margin-bottom: 8px;
}

.attr-list, .conn-list {
    display: flex;
    flex-direction: column;
    gap: 6px;
}

.attr-item {
    font-size: 11px;
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    align-items: baseline;
    padding: 4px;
    background: #F9F9F9;
    border-radius: 4px;
}

.attr-name {
    font-family: 'JetBrains Mono', monospace;
    font-weight: 600;
    color: #000;
}

.attr-type {
    color: #999;
    font-size: 10px;
}

.attr-desc {
    color: #555;
    flex: 1;
    min-width: 150px;
}

.example-list {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
}

.example-tag {
    font-size: 11px;
    background: #FFF;
    border: 1px solid #E0E0E0;
    padding: 3px 8px;
    border-radius: 12px;
    color: #555;
}

.conn-item {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 11px;
    padding: 6px;
    background: #F5F5F5;
    border-radius: 4px;
    font-family: 'JetBrains Mono', monospace;
}

.conn-node {
    font-weight: 600;
    color: #333;
}

.conn-arrow {
    color: #BBB;
}

/* Step 02 Stats */
.stats-grid {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 12px;
  background: #F9F9F9;
  padding: 16px;
  border-radius: 6px;
}

.stat-card {
  text-align: center;
}

.stat-value {
  display: block;
  font-size: 20px;
  font-weight: 700;
  color: #000;
  font-family: 'JetBrains Mono', monospace;
}

.stat-label {
  font-size: 9px;
  color: #999;
  text-transform: uppercase;
  margin-top: 4px;
  display: block;
}

/* Step 03 Button */
.action-btn {
  width: 100%;
  background: #000;
  color: #FFF;
  border: none;
  padding: 14px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s;
}

.action-btn:hover:not(:disabled) {
  opacity: 0.8;
}

.action-btn:disabled {
  background: #CCC;
  cursor: not-allowed;
}

.progress-section {
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 12px;
  color: #FF5722;
  margin-bottom: 12px;
}

.spinner-sm {
  width: 14px;
  height: 14px;
  border: 2px solid #FFCCBC;
  border-top-color: #FF5722;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin { to { transform: rotate(360deg); } }

/* System Logs */
.system-logs {
  background: #000;
  color: #DDD;
  padding: 16px;
  font-family: 'JetBrains Mono', monospace;
  border-top: 1px solid #222;
  flex-shrink: 0;
}

.log-header {
  display: flex;
  justify-content: space-between;
  border-bottom: 1px solid #333;
  padding-bottom: 8px;
  margin-bottom: 8px;
  font-size: 10px;
  color: #888;
}

.log-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
  height: 80px; /* Approx 4 lines visible */
  overflow-y: auto;
  padding-right: 4px;
}

.log-content::-webkit-scrollbar {
  width: 4px;
}

.log-content::-webkit-scrollbar-thumb {
  background: #333;
  border-radius: 2px;
}

.log-line {
  font-size: 11px;
  display: flex;
  gap: 12px;
  line-height: 1.5;
}

.log-time {
  color: #666;
  min-width: 75px;
}

.log-msg {
  color: #CCC;
  word-break: break-all;
}
</style>
